import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Tetris.module.css";

import MainBoard from "../component/tetris/MainBoard";
import SideBoard from "../component/tetris/SideBoard";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <MainBoard />
                <SideBoard />
            </main>
        </div>
    );
}
